hyperopt:
  lr: ["uniform", [0.0001, 0.005]]
  nsteps: ["choice", [20, 30, 40, 50, 60]]
  gamma: ["uniform", [0.91, 0.99]]
  beta_entropy: ["uniform", [0.001, 0.1]]
  hidden_size: ["choice", [24, 32, 64]]

good_inits:
  - lr: 0.0007
    gamma: 0.99
    nsteps: 3
    beta_entropy: 0.001
    hidden_size: 2
  - lr: 0.001
    gamma: 0.99
    nsteps: 3
    beta_entropy: 0.001
    hidden_size: 2
  - lr: 0.0009
    gamma: 0.93
    nsteps: 4
    beta_entropy: 0.02
    hidden_size: 2
  - lr: 0.0004
    gamma: 0.91
    nsteps: 4
    beta_entropy: 0.01
    hidden_size: 2
