experiment: a2c-pre
algo: a2c
env_name: LunarLander-v2
base_seed: 42

training_steps: 4000000
gamma: 0.99
nsteps: 50
beta_entropy: 0.001
lr: 0.001
hidden_size: 64

val_frequency: 25000  # steps
val_episodes: 100

save_agent: yes

log:
  frequency: 100  # episodes
  detailed: False

model_state: "results/2019Dec18-164937_expert_critic/0000_a2c_ll/9/policy_step_3775000.pth"
freeze_critic: no
