experiment: a2c-pre
algo: a2c
env_name: LunarLander-v2
base_seed: 42

training_steps: 1000000
gamma: 0.99
nsteps: 50
beta_entropy: 0.001
lr: 0.001
hidden_size: 64

log_frequency: 100  # episodes
val_frequency: 25000  # steps
val_episodes: 100

save_agent: yes

model_state: "results/2019Dec06-140540_a2c_ll/0000_a2c_ll/0/policy_step_0075000.pth"
freeze_critic: no