hyperopt:
  lr: ["uniform", [0.0001, 0.01]]
  nsteps: ["choice", [10, 20, 30, 40, 50, 60, 70]]
  gamma: ["uniform", [0.91, 0.99]]
  beta_entropy: ["uniform", [0.0001, 0.1]]
  hidden_size: ["choice", [24, 32, 64, 128]]

good_inits:
  - lr: 0.0007
    gamma: 0.99
    nsteps: 4
    beta_entropy: 0.001
    hidden_size: 2
  - lr: 0.001
    gamma: 0.99
    nsteps: 4
    beta_entropy: 0.001
    hidden_size: 2