
experiment: neac_llc
algo: neac
env_name: LunarLanderContinuous-v2
base_seed: 42

dnd:
  size: 5_000
  key_size: 24
  lr: 0.47
  use_critic_grads: True

training_steps: 1000000
gamma: 0.99
nsteps: 30
beta_entropy: 0.087
lr: 0.00059

log_frequency: 100  # episodes
val_frequency: 25000 # steps
val_episodes: 100