experiment: fine_neac_lld
algo: neac
env_name: LunarLander-v2
base_seed: 42
training_steps: 2000000
dnd: 
  size: 20000
  key_size: 64
  knn_no: 8
  lr: 0.641
  lr_schedule: 
    end: 0.01
    steps: 1000000
  use_critic_grads: False
gamma: 0.97
nsteps: 50
beta_entropy: 0.089
lr: 0.0031
log_frequency: 100
val_frequency: 25000
val_episodes: 100