experiment: neac_lld
algo: neac
env_name: LunarLander-v2
base_seed: 42
training_steps: 2000000
dnd: 
  size: 3000
  key_size: 32
  knn_no: 16
  lr: 0.43
  lr_schedule: 
    end: 0.01
    steps: 2000000
  use_critic_grads: False
gamma: 0.91
nsteps: 50
beta_entropy: 0.001
lr: 0.002
log_frequency: 100
val_frequency: 25000
val_episodes: 100