experiment: fine_neac_lld
algo: neac
env_name: LunarLander-v2
base_seed: 42
training_steps: 2000000
dnd: 
  size: 10000
  key_size: 24
  knn_no: 16
  lr: 0.29
  lr_schedule: 
    end: 0.01
    steps: 2000000
  use_critic_grads: True
gamma: 0.96
nsteps: 50
beta_entropy: 0.070
lr: 0.001
log_frequency: 100
val_frequency: 25000
val_episodes: 100