experiment: neac_lld
algo: neac
env_name: LunarLander-v2
base_seed: 42
training_steps: 2000000
dnd: 
  size: 20000
  key_size: 64
  knn_no: 16
  lr: 0.10
  lr_schedule: 
    end: 0.01
    steps: 2000000
  use_critic_grads: True
gamma: 0.93
nsteps: 60
beta_entropy: 0.038
lr: 0.0026
log_frequency: 100
val_frequency: 25000
val_episodes: 100