hyperopt:
  lr: ["uniform", [0.0001, 0.005]]
  nsteps: ["choice", [20, 30, 40, 50, 60]]
  gamma: ["uniform", [0.91, 0.99]]
  beta_entropy: ["uniform", [0.001, 0.1]]
  hidden_size: ["choice", [24, 32, 64]]
